# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-26 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(blank=True, default=False, max_length=50)),
                ('lname', models.CharField(blank=True, default=False, max_length=50)),
                ('phone', models.CharField(blank=True, default=False, max_length=50)),
                ('avscore', models.CharField(blank=True, default=False, max_length=50)),
                ('num_free', models.CharField(blank=True, default=False, max_length=50)),
            ],
            options={
                'permissions': (('view_customer', 'View Customer'), ('edit_customer', 'Edit Customer')),
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('fname', models.CharField(blank=True, default=False, max_length=50)),
                ('lname', models.CharField(blank=True, default=False, max_length=50)),
                ('fullname', models.CharField(blank=True, default=False, max_length=50)),
                ('phone', models.CharField(blank=True, default=False, max_length=50)),
                ('score', models.FloatField()),
                ('avscore', models.CharField(blank=True, default=False, max_length=50)),
                ('fscore', models.CharField(blank=True, default=False, max_length=50)),
            ],
        ),
    ]
