# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-26 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Reward', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, default=False, max_length=20)),
                ('sname', models.CharField(blank=True, default=False, max_length=30)),
                ('page', models.IntegerField(blank=True, default=False)),
                ('gender', models.CharField(blank=True, default=False, max_length=30)),
                ('telno', models.CharField(blank=True, default=False, max_length=20)),
                ('username', models.CharField(blank=True, default=False, max_length=20)),
                ('password', models.CharField(default=False, max_length=50)),
                ('email', models.CharField(blank=True, default=False, max_length=50)),
                ('street', models.CharField(blank=True, default=False, max_length=50)),
                ('city', models.CharField(blank=True, default=False, max_length=20)),
                ('state', models.CharField(blank=True, default=False, max_length=20)),
                ('role2', models.CharField(default=False, max_length=20)),
                ('access_right', models.CharField(default=False, max_length=30)),
                ('account_blocked', models.BooleanField(default=False)),
                ('profphoto', models.ImageField(default=False, upload_to='uploads/')),
                ('code', models.CharField(blank=True, default=False, max_length=12)),
                ('reward_amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=16)),
                ('user', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='register', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('view_register', 'View Register'), ('edit_register', 'Edit Register')),
            },
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
