# Generated by Django 3.0.3 on 2021-07-26 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0002_register_userdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={},
        ),
    ]
