# Generated by Django 3.0.5 on 2021-07-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0003_auto_20210726_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avscore',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='avscore',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
    ]
