# Generated by Django 3.0.5 on 2021-07-27 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reward', '0005_auto_20210727_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='avscore',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
